{{- if not .Values.jenkinsSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: rumis-api-secret
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.auth.adminPassword | b64enc }}
  AUTH_ENCRYPTION_PASSWORD: {{ .Values.auth.encryptionPassword | b64enc }}
  AUTH_ENCRYPTION_SALT: {{ .Values.auth.encryptionSalt | b64enc }}
  AUTH_TICKET_PASSWORD: {{ .Values.auth.ticketPassword | b64enc }}
  AUTH_TOKEN_SECURITY_KEY: {{ .Values.auth.tokenSecurityKey | b64enc }}
  AUTH_USER_PROFILE_TOKEN_SECURITY_KEY: {{ .Values.auth.userProfile.tokenSecurityKey | b64enc }}
  DATABASE_CONNECTION_STRING: {{ .Values.connectionStrings.rumisDatabase | b64enc }}
  REDIS_CONNECTION_STRING: {{ .Values.connectionStrings.redis | b64enc }}
  S3_ACCESS_KEY: '{{ .Values.s3.accessKey | b64enc }}'
  S3_SECRET_KEY: '{{ .Values.s3.accessSecret | b64enc }}'
  {{- if .Values.smtp.password }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc }}
  {{- end }}
  {{- if .Values.smtp.username }}
  SMTP_USERNAME: {{ .Values.smtp.username | b64enc }}
  {{- end }}
  VIIS_CREDENTIALS_PASSWORD: '{{ .Values.viis.password | b64enc }}'
  VIIS_CREDENTIALS_USERNAME: '{{ .Values.viis.username | b64enc }}'
  VRAA_CLIENT_ID: {{ .Values.vraa.clientId | b64enc }}
  VRAA_CLIENT_SECRET: {{ .Values.vraa.clientSecret | b64enc }}
{{- end }}
