{{- if not .Values.jenkinsSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: rumis-auth-secret
type: Opaque
data:
  ADFS_METADATA_ADDRESS: {{ .Values.adfs.metadataaddress | b64enc }}
  ADFS_WTREALM: {{ .Values.adfs.wtrealm | b64enc }}
  DATABASE_CONNECTION_STRING: {{ .Values.connectionStrings.rumisDatabase | b64enc }}
  TICKET_PASSWORD: {{ .Values.auth.ticketPassword | b64enc }}
  TICKET_REPLY_URL: {{ .Values.auth.ticketReplyUrl | b64enc }}
{{- end }}
