{{- if not .Values.jenkinsSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: rumis-tasks-secret
type: Opaque
data:
  DATABASE_CONNECTION_STRING: {{ .Values.connectionStrings.rumisDatabase | b64enc }}
  REDIS_CONNECTION_STRING: {{ .Values.connectionStrings.redis | b64enc }}
  VIIS_CREDENTIALS_PASSWORD: '{{ .Values.viis.password | b64enc }}'
  VIIS_CREDENTIALS_USERNAME: '{{ .Values.viis.username | b64enc }}'
{{- end }}