{{- if not .Values.jenkinsSecrets }}
{{- if and (not .Values.tls.secretName) (eq .Values.tls.enabled true) }}
apiVersion: v1
kind: Secret
metadata:
  name: rumis-tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
type: kubernetes.io/tls
{{- end }}
{{- end }}