apiVersion: v1
kind: Service
metadata:
  name: rumis-app
spec:
  selector:
    app: rumis-app
  ports:
  - port: 80
    targetPort: 3000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
