kind: ConfigMap
apiVersion: v1
metadata:
  name: rumis-tasks-config
data:
  DOTNET_ENVIRONMENT: {{ .Values.environment }}
  MYSQL_VERSION: '{{ .Values.mysql.version }}'
  SESSION_IDLE_TIMEOUT_IN_MINUTES: '{{ .Values.auth.idleTimeoutInMinutes }}'
  VISS_SERVICE_ENDPOINT_ADDRESS: {{ .Values.viis.endpointUrl }}