//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIIS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamBase", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamDateTime))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamBool))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamInt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamDecimal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamListOfInts))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VIIS.QueryParamListOfStrings))]
    public partial class QueryParamBase : object
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamDateTime", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamDateTime : VIIS.QueryParamBase
    {
        
        private System.DateTime ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamBool", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamBool : VIIS.QueryParamBase
    {
        
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamInt", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamInt : VIIS.QueryParamBase
    {
        
        private int ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamString", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamString : VIIS.QueryParamBase
    {
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamDecimal", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamDecimal : VIIS.QueryParamBase
    {
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamListOfInts", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamListOfInts : VIIS.QueryParamBase
    {
        
        private int[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryParamListOfStrings", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class QueryParamListOfStrings : VIIS.QueryParamBase
    {
        
        private string[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UdsFilterInfoSturcture", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class UdsFilterInfoSturcture : object
    {
        
        private string FilterCodeField;
        
        private VIIS.UdsExecuteInputParameterInfo[] InputParametersField;
        
        private System.Xml.XmlElement ResultXsdField;
        
        private string SoapCallExampleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilterCode
        {
            get
            {
                return this.FilterCodeField;
            }
            set
            {
                this.FilterCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VIIS.UdsExecuteInputParameterInfo[] InputParameters
        {
            get
            {
                return this.InputParametersField;
            }
            set
            {
                this.InputParametersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.XmlElement ResultXsd
        {
            get
            {
                return this.ResultXsdField;
            }
            set
            {
                this.ResultXsdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoapCallExample
        {
            get
            {
                return this.SoapCallExampleField;
            }
            set
            {
                this.SoapCallExampleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UdsExecuteInputParameterInfo", Namespace="http://schemas.datacontract.org/2004/07/VIIS2WebService.Model")]
    public partial class UdsExecuteInputParameterInfo : object
    {
        
        private bool IsMandatoryField;
        
        private string ParameterNameField;
        
        private string ParameterTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMandatory
        {
            get
            {
                return this.IsMandatoryField;
            }
            set
            {
                this.IsMandatoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName
        {
            get
            {
                return this.ParameterNameField;
            }
            set
            {
                this.ParameterNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterType
        {
            get
            {
                return this.ParameterTypeField;
            }
            set
            {
                this.ParameterTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VIIS.IUniversalDataSetService")]
    public interface IUniversalDataSetService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversalDataSetService/Execute", ReplyAction="http://tempuri.org/IUniversalDataSetService/ExecuteResponse")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> ExecuteAsync(string dataSetFilterCode, VIIS.QueryParamBase[] queryParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversalDataSetService/ExecuteIncremental", ReplyAction="http://tempuri.org/IUniversalDataSetService/ExecuteIncrementalResponse")]
        System.Threading.Tasks.Task<System.Xml.XmlElement> ExecuteIncrementalAsync(string dataSetFilterCode, VIIS.QueryParamBase[] queryParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversalDataSetService/GetQuerySchema", ReplyAction="http://tempuri.org/IUniversalDataSetService/GetQuerySchemaResponse")]
        System.Threading.Tasks.Task<VIIS.UdsFilterInfoSturcture> GetQuerySchemaAsync(string dataSetFilterCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUniversalDataSetService/ApproveIncrementalRequest", ReplyAction="http://tempuri.org/IUniversalDataSetService/ApproveIncrementalRequestResponse")]
        System.Threading.Tasks.Task<bool> ApproveIncrementalRequestAsync(string dataSetFilterCode, System.Guid requestId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IUniversalDataSetServiceChannel : VIIS.IUniversalDataSetService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class UniversalDataSetServiceClient : System.ServiceModel.ClientBase<VIIS.IUniversalDataSetService>, VIIS.IUniversalDataSetService
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UniversalDataSetServiceClient() : 
                base(UniversalDataSetServiceClient.GetDefaultBinding(), UniversalDataSetServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUniversalDataSetService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniversalDataSetServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UniversalDataSetServiceClient.GetBindingForEndpoint(endpointConfiguration), UniversalDataSetServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniversalDataSetServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UniversalDataSetServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniversalDataSetServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UniversalDataSetServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UniversalDataSetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> ExecuteAsync(string dataSetFilterCode, VIIS.QueryParamBase[] queryParams)
        {
            return base.Channel.ExecuteAsync(dataSetFilterCode, queryParams);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlElement> ExecuteIncrementalAsync(string dataSetFilterCode, VIIS.QueryParamBase[] queryParams)
        {
            return base.Channel.ExecuteIncrementalAsync(dataSetFilterCode, queryParams);
        }
        
        public System.Threading.Tasks.Task<VIIS.UdsFilterInfoSturcture> GetQuerySchemaAsync(string dataSetFilterCode)
        {
            return base.Channel.GetQuerySchemaAsync(dataSetFilterCode);
        }
        
        public System.Threading.Tasks.Task<bool> ApproveIncrementalRequestAsync(string dataSetFilterCode, System.Guid requestId)
        {
            return base.Channel.ApproveIncrementalRequestAsync(dataSetFilterCode, requestId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUniversalDataSetService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUniversalDataSetService))
            {
                return new System.ServiceModel.EndpointAddress("https://is.test.viis.gov.lv:442/Services/UniversalDataSetService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UniversalDataSetServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUniversalDataSetService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UniversalDataSetServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUniversalDataSetService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUniversalDataSetService,
        }
    }
}
